# Generated by Django 6.1.2 on 2026-10-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('currency', models.CharField(help_text='"USD", "EUR"… or "ALL".', max_length=4)),
                ('time', models.DateTimeField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('holiday', 'Holiday')], max_length=10)),
                ('forecast', models.CharField(blank=True, max_length=30)),
                ('previous', models.CharField(blank=True, max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['time'], name='news_econom_time_f8e664_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'currency', 'time'), name='unique_event')],
            },
        ),
    ]
