# Generated by Django 6.1.2 on 2026-10-07 18:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_instrument_spread_pips'),
        ('signals', '0003_strategyprofile_avoid_crowded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. Off = no new trades are opened.')),
                ('account_id', models.CharField(blank=True, help_text='OANDA account ID, e.g. "101-004-1234567-001".', max_length=40)),
                ('allow_live', models.BooleanField(default=False, help_text='Required before trading a LIVE (real money) OANDA account.')),
                ('risk_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Account balance risked per trade (%), if the stop loss is hit.', max_digits=4)),
                ('max_open_trades', models.PositiveSmallIntegerField(default=3, help_text='Never more open trades than this.')),
                ('daily_loss_limit', models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='Stop opening trades for the day after losing this % of the account.', max_digits=4)),
                ('weekly_loss_limit', models.DecimalField(decimal_places=1, default=Decimal('6.0'), help_text='Stop opening trades for the week after losing this %.', max_digits=4)),
                ('max_slippage_r', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Skip a signal if price has already moved against it by more than this fraction of the stop distance (0.25 = a quarter of the risk).', max_digits=3)),
                ('min_confidence', models.PositiveSmallIntegerField(default=0, help_text='Only trade signals with at least this confidence (%). 0 = trade every signal.')),
                ('close_on_expiry', models.BooleanField(default=True, help_text='Close a trade at market when its signal expires, as the backtest does.')),
                ('day_start', models.DateField(blank=True, editable=False, null=True)),
                ('day_start_nav', models.FloatField(blank=True, editable=False, null=True)),
                ('week_start', models.DateField(blank=True, editable=False, null=True)),
                ('week_start_nav', models.FloatField(blank=True, editable=False, null=True)),
                ('halted_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('halt_reason', models.CharField(blank=True, editable=False, max_length=200)),
                ('last_sync_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.CharField(blank=True, editable=False, max_length=255)),
                ('account_currency', models.CharField(blank=True, editable=False, max_length=4)),
                ('balance', models.FloatField(blank=True, editable=False, null=True)),
                ('nav', models.FloatField(blank=True, editable=False, null=True)),
                ('strategies', models.ManyToManyField(blank=True, help_text='Strategies whose signals are traded. None ticked = all active.', to='signals.strategyprofile')),
            ],
            options={
                'verbose_name': 'Auto-trader',
                'verbose_name_plural': 'Auto-trader',
            },
        ),
        migrations.CreateModel(
            name='BrokerTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(default='practice', max_length=10)),
                ('direction', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Placing'), ('open', 'Open'), ('closed', 'Closed'), ('skipped', 'Skipped'), ('rejected', 'Rejected by broker'), ('error', 'Error')], default='pending', max_length=10)),
                ('units', models.IntegerField(default=0)),
                ('requested_price', models.FloatField(blank=True, null=True)),
                ('fill_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('risk_amount', models.FloatField(blank=True, help_text='Planned loss at the stop, account currency.', null=True)),
                ('broker_trade_id', models.CharField(blank=True, max_length=40)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=20)),
                ('realized_pl', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_trades', to='market.instrument')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_trade', to='signals.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
