# Generated by Django 6.1.2 on 2026-10-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Display name, e.g. "EUR/USD".', max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('forex', 'Forex'), ('metal', 'Metal')], default='forex', max_length=10)),
                ('pip_size', models.DecimalField(decimal_places=6, help_text='0.0001 for most pairs, 0.01 for JPY pairs, 0.1 for gold.', max_digits=10)),
                ('decimals', models.PositiveSmallIntegerField(default=5, help_text='Decimals shown for prices.')),
                ('yahoo_symbol', models.CharField(blank=True, help_text='e.g. "EURUSD=X", gold "GC=F".', max_length=30)),
                ('twelvedata_symbol', models.CharField(blank=True, help_text='e.g. "EUR/USD", "XAU/USD".', max_length=30)),
                ('oanda_symbol', models.CharField(blank=True, help_text='e.g. "EUR_USD", "XAU_USD".', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], max_length=4)),
                ('time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market.instrument')),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-time'], name='market_cand_instrum_764ac8_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'timeframe', 'time'), name='unique_candle')],
            },
        ),
    ]
