# Generated by Django 6.1.2 on 2026-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='spread_pips',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Typical spread in pips. Backtests charge it on every trade.', max_digits=6),
        ),
    ]
