# Generated by Django 6.1.2 on 2026-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(choices=[('yahoo', 'Yahoo Finance (free, no key, slight delay)'), ('twelvedata', 'Twelve Data (free key, 800 requests/day)'), ('oanda', 'OANDA (free practice account token)')], default='yahoo', max_length=20)),
                ('twelvedata_api_key', models.CharField(blank=True, max_length=120)),
                ('oanda_api_token', models.CharField(blank=True, max_length=200)),
                ('oanda_environment', models.CharField(choices=[('practice', 'Practice (demo)'), ('live', 'Live')], default='practice', max_length=10)),
                ('engine_interval_minutes', models.PositiveSmallIntegerField(default=5, help_text='How often the analysis runs (minutes).')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Your chat or group ID.', max_length=100)),
                ('alert_emails', models.TextField(blank=True, help_text='One email address per line.')),
                ('alert_on_close', models.BooleanField(default=True, help_text='Also alert when a signal hits TP or SL.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
