# Generated by Django 6.1.2 on 2026-10-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_fetched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_ok_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Last successful economic calendar download.', null=True),
        ),
    ]
