# Generated by Django 6.1.2 on 2026-10-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_calendar_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_discover',
            field=models.BooleanField(default=True, help_text='Let the system build and test new strategies by itself, and switch on ones that pass.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_every_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='How often it searches (days).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='macro_fetched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_discovered_active',
            field=models.PositiveSmallIntegerField(default=3, help_text='At most this many discovered strategies switched on at once.'),
        ),
    ]
