# Generated by Django 6.1.2 on 2026-10-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4)),
                ('report_date', models.DateField(help_text='Positions as of this Tuesday; published the following Friday.')),
                ('long', models.IntegerField()),
                ('short', models.IntegerField()),
                ('open_interest', models.IntegerField()),
            ],
            options={
                'ordering': ['report_date'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'report_date'), name='unique_cot')],
            },
        ),
        migrations.CreateModel(
            name='MacroBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField(help_text='Trading day (exchange time).')),
                ('close', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='unique_macro_bar')],
            },
        ),
    ]
