# Generated by Django 6.1.2 on 2026-10-07 11:31

import apps.signals.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_timeframe', models.CharField(choices=[('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], default='15m', help_text='Timeframe used to time the entry.', max_length=4)),
                ('confirm_timeframes', models.JSONField(blank=True, default=apps.signals.models.default_confirm, help_text='Higher timeframes that must agree on the trend.')),
                ('require_all_confirm', models.BooleanField(default=True, help_text='On: every confirmation timeframe must agree. Off: most must agree.')),
                ('risk_reward', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Take profit distance as a multiple of the stop loss distance.', max_digits=4)),
                ('sl_method', models.CharField(choices=[('swing', 'Below/above the last swing point'), ('atr', 'A multiple of ATR (average range)')], default='swing', max_length=10)),
                ('atr_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Stop distance in ATRs (ATR method, and the fallback for swing).', max_digits=4)),
                ('min_score', models.PositiveSmallIntegerField(default=65, help_text='Minimum setup score (0-100) to say TRADE NOW.')),
                ('alert_min_confidence', models.PositiveSmallIntegerField(default=60, help_text='Only alert when confidence is at least this (%).')),
                ('adx_threshold', models.PositiveSmallIntegerField(default=20, help_text='ADX needed to call the market trending.')),
                ('ema_fast', models.PositiveSmallIntegerField(default=20)),
                ('ema_mid', models.PositiveSmallIntegerField(default=50)),
                ('ema_slow', models.PositiveSmallIntegerField(default=200)),
                ('rsi_length', models.PositiveSmallIntegerField(default=14)),
                ('sessions', models.JSONField(blank=True, default=apps.signals.models.default_sessions, help_text='Only signal during these sessions. Empty = any time the market is open.')),
                ('max_hold_bars', models.PositiveSmallIntegerField(default=48, help_text='Close the signal as expired after this many entry candles.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instruments', models.ManyToManyField(blank=True, help_text='Leave empty to analyse all active pairs.', to='market.instrument')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=4)),
                ('candle_time', models.DateTimeField(help_text='Close of the candle that produced the signal (UTC).')),
                ('entry', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('risk_reward', models.FloatField()),
                ('score', models.PositiveSmallIntegerField()),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('tp', 'Take profit hit'), ('sl', 'Stop loss hit'), ('expired', 'Expired')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('result_r', models.FloatField(blank=True, null=True)),
                ('pips', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='market.instrument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signals.strategyprofile')),
            ],
            options={
                'ordering': ['-candle_time'],
            },
        ),
        migrations.CreateModel(
            name='PairState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(default='wait', max_length=10)),
                ('direction', models.CharField(blank=True, max_length=4)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('entry', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('candle_time', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='market.instrument')),
                ('active_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signals.signal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='signals.strategyprofile')),
            ],
            options={
                'ordering': ['instrument__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('trades', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('expired', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('avg_r', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('total_r', models.FloatField(default=0)),
                ('buckets', models.JSONField(blank=True, default=dict)),
                ('per_pair', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='signals.strategyprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('profile', 'instrument', 'candle_time'), name='one_signal_per_candle'),
        ),
        migrations.AddConstraint(
            model_name='pairstate',
            constraint=models.UniqueConstraint(fields=('profile', 'instrument'), name='one_state_per_pair'),
        ),
    ]
