# Generated by Django 6.1.2 on 2026-10-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyprofile',
            name='auto_tune',
            field=models.BooleanField(default=True, help_text='Let the system test and improve these settings by itself.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='last_tuned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='news_filter',
            field=models.BooleanField(default=True, help_text='Say WAIT around high-impact economic news.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='news_include_medium',
            field=models.BooleanField(default=False, help_text='Also avoid medium-impact news.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='news_minutes_after',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minutes after the release.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='news_minutes_before',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minutes before the release.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='tune_every_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='How often it re-tests itself (days).'),
        ),
        migrations.CreateModel(
            name='TuningRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('adopted', 'Better settings adopted'), ('kept', 'Current settings kept'), ('failed', 'Could not run')], default='kept', max_length=10)),
                ('has_edge', models.BooleanField(default=False, help_text='The settings in use were profitable on unseen data.')),
                ('variations', models.PositiveIntegerField(default=0)),
                ('train_start', models.DateTimeField(blank=True, null=True)),
                ('test_start', models.DateTimeField(blank=True, null=True)),
                ('test_end', models.DateTimeField(blank=True, null=True)),
                ('previous_params', models.JSONField(blank=True, default=dict)),
                ('best_params', models.JSONField(blank=True, default=dict)),
                ('current_train', models.JSONField(blank=True, default=dict)),
                ('current_test', models.JSONField(blank=True, default=dict)),
                ('best_train', models.JSONField(blank=True, default=dict)),
                ('best_test', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('reverted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunings', to='signals.strategyprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
