# Generated by Django 6.1.2 on 2026-10-07 17:21

import apps.signals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_strategyprofile_auto_tune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyprofile',
            name='avoid_crowded',
            field=models.BooleanField(default=False, help_text='Skip trades where speculators are at a 3-year positioning extreme.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='discovered',
            field=models.BooleanField(default=False, editable=False, help_text='Built by the system; switched off automatically if it stops working.'),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='macro_filter',
            field=models.CharField(choices=[('off', "Show only (don't block trades)"), ('not_against', 'Block trades they point against'), ('aligned', 'Trade only when they support the direction')], default='off', help_text='How fundamentals and sentiment affect decisions.', max_length=12),
        ),
        migrations.AddField(
            model_name='strategyprofile',
            name='setups',
            field=models.JSONField(blank=True, default=apps.signals.models.default_setups, help_text='Entry setups this strategy trades.'),
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('combinations', models.PositiveIntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('created', models.ManyToManyField(blank=True, related_name='discovered_by', to='signals.strategyprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
